blueprint:
  name: "Botão Script-IR (Curto/Longo)"
  description: "Executa um script para clique curto e outro para clique longo, sem ciclos."
  domain: automation
  input:
    button_id_input:
      name: "ID do Botão"
      description: "ID enviado pelo ESP (ex: botao_tv)"
    script_curto:
      name: "Script Clique Curto"
      selector:
        entity:
          domain: script
    script_longo:
      name: "Script Clique Longo"
      selector:
        entity:
          domain: script

mode: queued
max: 10

trigger:
  - platform: event
    event_type: esphome.esp_click_event

action:
  - variables:
      evento_botao: "{{ trigger.event.data.button }}"
      evento_tipo: "{{ trigger.event.data.type }}"
      id_configurado: !input button_id_input

  # Filtra se o evento pertence a este botão
  - condition: template
    value_template: "{{ evento_botao == id_configurado }}"

  - choose:
      # --- LÓGICA CLIQUE CURTO ---
      - conditions: "{{ evento_tipo == 'curto' }}"
        sequence:
          - service: script.turn_on
            target:
              entity_id: !input script_curto

      # --- LÓGICA CLIQUE LONGO ---
      - conditions: "{{ evento_tipo == 'longo' }}"
        sequence:
          - service: script.turn_on
            target:
              entity_id: !input script_longo
